#!/usr/bin/env python

Import("env")
Import("env_modules")

env_godot_ai = env_modules.Clone()

env_godot_ai.add_source_files(env.modules_sources, "*.cpp")
env_godot_ai.add_source_files(env.modules_sources, "tools/*.cpp")
