"""Compile the shipped skills into the binary.

They used to be files in `misc/godot_ai/skills/`, which is a place nothing looks. Skill
discovery reads a project's `ai_skills/`, an addon's, and the editor's user data
directory - and none of those exist in a project someone has just made. So `--list-prompts`
answered `{"prompts": []}` on every real project, while the end-to-end suite passed
because it *copies* a skill into its own test project first.

That is worth spelling out, because the whole design rests on it: the skills are meant to
be the way in, offered ahead of a large tool registry, and shipping them as documentation in
the repository meant they were the way in for nobody. Two independent agents handed this
interface for the first time both reported the front door opening onto an empty room.

Compiled in, they travel with the editor the way the tool descriptions do.
"""

import os


def make_builtin_skills(target, source, env):
    root = os.path.join(env.Dir("#").abspath, "misc", "godot_ai", "skills")
    entries = []
    if os.path.isdir(root):
        for name in sorted(os.listdir(root)):
            path = os.path.join(root, name, "SKILL.md")
            if not os.path.isfile(path):
                continue
            with open(path, "r", encoding="utf-8") as handle:
                entries.append((name, handle.read()))

    def as_c_string(text):
        # Encoded byte by byte as escapes rather than pasted in as a literal: the text is
        # UTF-8 prose full of quotes, backslashes and long lines, and a String built from
        # a raw literal reads it as Latin-1 anyway.
        out = []
        for byte in text.encode("utf-8"):
            out.append("\\x%02x" % byte)
        # MSVC caps a string literal at 16380 bytes and these run past it, so the escapes
        # are emitted in chunks that the compiler concatenates.
        chunks = []
        for start in range(0, len(out), 1000):
            chunks.append('"%s"' % "".join(out[start:start + 1000]))
        return "\n\t\t".join(chunks) if chunks else '""'

    with open(str(target[0]), "w", encoding="utf-8") as handle:
        handle.write("/* THIS FILE IS GENERATED by modules/godot_ai/skills_builder.py. */\n")
        handle.write("/* Edit the skills under misc/godot_ai/skills/ instead.          */\n\n")
        handle.write("#ifndef MCP_BUILTIN_SKILLS_GEN_H\n#define MCP_BUILTIN_SKILLS_GEN_H\n\n")
        handle.write("struct MCPBuiltinSkillSource {\n\tconst char *name;\n\tconst char *text;\n};\n\n")
        handle.write("inline constexpr MCPBuiltinSkillSource MCP_BUILTIN_SKILLS[] = {\n")
        for name, text in entries:
            handle.write('\t{ "%s",\n\t\t%s },\n' % (name, as_c_string(text)))
        handle.write("\t{ nullptr, nullptr },\n};\n\n")
        handle.write("#endif // MCP_BUILTIN_SKILLS_GEN_H\n")
